include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.chopper.dart
    - lib/generated_plugin_registrant.dart
    - android
    - .fvm
    - .idea
    - assets
    - build
    - ios
    - linux
    - macos
    - web
    - windows
    - .dart_tool

linter:
  rules:
    library_private_types_in_public_api: false
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
    avoid_unused_constructor_parameters: false
    avoid_print: true
    prefer_single_quotes: true
